### PR TITLE
Fix #87: Test use MailpitException which is a RuntimeException

### LINKED ISSUE #87: Question - why do all the Mailbox methods throw `ApiException`?
I find it very hard to use because all the methods on `Mailbox` throw `ApiException`, which is a checked exception. It reminds me of things in the `java.io` and `java.sql` packages. It also makes using streams/lambdas/etc very difficult.

Could/should `ApiException` be a `RuntimeException`? I see that the class is generated, so if there isn't a way to have it generated as a runtime exception, maybe invent another one and then add the try/catch/re-throw to the methods in `Mailbox`?

### PR DESCRIPTION
**Pull request by melloware**
Fix #87: Test use MailpitException which is a RuntimeException

### CODE REVIEW

**Comment by edeandrea** [comment]
You don't need to specifically throw `MailpitException` anymore...

There's also a Java generics "trick" you can use, using type erasure, to trick the compiler into being able to treat a checked exception as a runtime exception.

```java
 private <T extends Throwable> void rethrow(Throwable x) throws T {
        throw (T) x;
    }
```

**Comment by melloware** [comment]
That feels like cheating :)

**Comment by edeandrea** [comment]
I stole that from Apache Commons Lang's ExceptionUtils class :)

**Comment by melloware** [comment]
OK I removed all the `throws` as not needed.

**Comment by edeandrea** [comment]
> That feels like cheating :)

It might be, but it's backwards compatible. By throwing `MailpitException` instead of `ApiException`, people's code will now fail to compile when they take this update.

Using the compiler trick, they can still catch `ApiException`, but they don't have to. And if anything fails, it still throws `ApiException`. Win-win :D

**Comment by melloware** [comment]
OK went with `rethrow`

**Pull request merged**
